POST http://localhost:5000/user
Content-Type: application/json

{
    "name": "User",
    "lastName": "User",
    "email": "user@user.com",
    "password": "user"
}

###

POST https://hulkstoreserver.herokuapp.com/user/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}

###
POST https://hulkstoreserver.herokuapp.com/products
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNTYwMmE3OTk2OTdiYWVlZTdlNDYwOCIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjMzMDMyMTk4LCJleHAiOjE2MzMxMTg1OTh9.Y8dryHIwcENzJt7ltVDA44w9XPVQUnqJ7o_NNctK2MU

{
    "name": "Product test2",
    "img": "#",
    "price": "100",
    "description": "Lorem ipsum",
    "stock": "10"
}

###
PATCH https://hulkstoreserver.herokuapp.com/products/615634e22260280b3c600b7f
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNTYwMmE3OTk2OTdiYWVlZTdlNDYwOCIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjMzMDMyMTk4LCJleHAiOjE2MzMxMTg1OTh9.Y8dryHIwcENzJt7ltVDA44w9XPVQUnqJ7o_NNctK2MU

{
    "name": "Product 4",
    "img": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pinterest.com%2Fpin%2F569098160981209852%2F&psig=AOvVaw3ZQZ_Z_Z_XZ_Z_Z_Z_Z_Z&ust=1589788240870000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCKDyP-x-4-gCFQAAAAAdAAAAABAD",
    "price": "100",
    "description": "Lorem ipsum",
    "stock": "10"
}

###
GET https://hulkstoreserver.herokuapp.com/products
Content-Type: application/json

###
GET http://localhost:5000/products/61561868922d0ecc49254d77
Content-Type: application/json

###
DELETE http://localhost:5000/products/6156324cca5969804095c009
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNTYwMmE3OTk2OTdiYWVlZTdlNDYwOCIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjMzMDMyMTk4LCJleHAiOjE2MzMxMTg1OTh9.Y8dryHIwcENzJt7ltVDA44w9XPVQUnqJ7o_NNctK2MU

###
POST http://localhost:5000/cart
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNTYwMmE3OTk2OTdiYWVlZTdlNDYwOCIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjMzMDMyMTk4LCJleHAiOjE2MzMxMTg1OTh9.Y8dryHIwcENzJt7ltVDA44w9XPVQUnqJ7o_NNctK2MU

{
    "productId": "615634e22260280b3c600b7f",
    "quantity": 1
}

###
GET https://hulkstoreserver.herokuapp.com/cart
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNTYwMmE3OTk2OTdiYWVlZTdlNDYwOCIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjMzMDMyMTk4LCJleHAiOjE2MzMxMTg1OTh9.Y8dryHIwcENzJt7ltVDA44w9XPVQUnqJ7o_NNctK2MU

###
DELETE https://hulkstoreserver.herokuapp.com/cart/6158d2cd2b3759e9694e75cc
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNTYwMmE3OTk2OTdiYWVlZTdlNDYwOCIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjMzMDMyMTk4LCJleHAiOjE2MzMxMTg1OTh9.Y8dryHIwcENzJt7ltVDA44w9XPVQUnqJ7o_NNctK2MU

###
PUT http://localhost:5000/cart/61563735e99a29568f1696e8
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNTYwMmE3OTk2OTdiYWVlZTdlNDYwOCIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjMzMDMyMTk4LCJleHAiOjE2MzMxMTg1OTh9.Y8dryHIwcENzJt7ltVDA44w9XPVQUnqJ7o_NNctK2MU

{
    "quantity": 3
}

###
POST http://localhost:5000/sales
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNTYwMmE3OTk2OTdiYWVlZTdlNDYwOCIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjMzMDMyMTk4LCJleHAiOjE2MzMxMTg1OTh9.Y8dryHIwcENzJt7ltVDA44w9XPVQUnqJ7o_NNctK2MU

{
    "paymentMethod": "cash",
    "address": "Calle falsa 123",
    "observation": "Lorem ipsum"
}

###
GET http://localhost:5000/sales
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNTYwMmE3OTk2OTdiYWVlZTdlNDYwOCIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjMzMDMyMTk4LCJleHAiOjE2MzMxMTg1OTh9.Y8dryHIwcENzJt7ltVDA44w9XPVQUnqJ7o_NNctK2MU



