
POST http://localhost:5000/recipes
Content-Type: application/json

{
    "title": "recipe 6",
    "img": "img112",
    "user": "6141811deeaa40803222901f",
    "ingredients": [ "ingredient 1", "ingredient 3", "ingredient 4" ],
    "category": "Veggies",
    "time":"23 minutos",
    "likes": 0,
    "steps": [ "step 1", "step 2", "step 3" ],
    "timeFridge": "2 dias",
    "timeFreezer": "5 dias",
    "tags": [ "tag 1", "tag 2", "tag 3" ]
}

###

GET https://polar-reaches-30197.herokuapp.com/recipes

###

GET http://localhost:5000/recipes/61381c56900dc801dc66035d

###

DELETE http://localhost:5000/recipes/61381c56900dc801dc66035d

###

PATCH https://polar-reaches-30197.herokuapp.com/recipes/614cf78336a60a190537def6
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzI0MzQxMDQsImV4cCI6MTYzMjUyMDUwNH0.bI25KNblg-_vs9wOjvCYsd0tn-77xasnrFM7YldtHTg

{
    "title": "recipe 112",
    "img": "img22",
    "user": "6141811deeaa40803222901f",
    "ingredients": [ "ingredient 2", "ingredient 4" ],
    "category": "Con carne",
    "time":"15 minutos",
    "likes": 12,
    "steps": [ "step 1", "step 2" ],
    "timeFridge": "20 minutos",
    "timeFreezer": "20 minutos",
    "tags": [ "tag 1", "tag 2" ]
}

###

GET http://localhost:5000/recipes/search?search=tag+1&searh=tag+2&field=tags

###

GET https://polar-reaches-30197.herokuapp.com/user/61422ef3257c69006799ed27
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDE4MTFkZWVhYTQwODAzMjIyOTAxZiIsImlhdCI6MTYzMTY4OTMwMywiZXhwIjoxNjMxNzc1NzAzfQ.zYvdpjTq4wJrul5dPEKP43Hrd35JsJYjpNWhfLcj4BQ

###
GET http://localhost:5000/user/61422ef3257c69006799ed27
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDE4MTFkZWVhYTQwODAzMjIyOTAxZiIsImlhdCI6MTYzMTY4OTMwMywiZXhwIjoxNjMxNzc1NzAzfQ.zYvdpjTq4wJrul5dPEKP43Hrd35JsJYjpNWhfLcj4BQ


###

POST http://localhost:5000/user
Content-Type: application/json

{
    "name" : "Loli",
    "lastName": "Avila",
    "email": "loli@gmail.com",
    "password": "loli",
    "role": "admin"
}

###
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "email": "loli@gmail.com",
    "password": "loli"
}

###

GET http://localhost:5000/notes/all/6141811deeaa40803222901f
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDE4MTFkZWVhYTQwODAzMjIyOTAxZiIsImlhdCI6MTYzMTY4OTMwMywiZXhwIjoxNjMxNzc1NzAzfQ.zYvdpjTq4wJrul5dPEKP43Hrd35JsJYjpNWhfLcj4BQ

###

GET http://localhost:5000/notes/6142373890e59ec0c14612f0
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDE4MTFkZWVhYTQwODAzMjIyOTAxZiIsImlhdCI6MTYzMTY4OTMwMywiZXhwIjoxNjMxNzc1NzAzfQ.zYvdpjTq4wJrul5dPEKP43Hrd35JsJYjpNWhfLcj4BQ

###

PATCH https://polar-reaches-30197.herokuapp.com/recipes/6142373890e59ec0c14612f0
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDE4MTFkZWVhYTQwODAzMjIyOTAxZiIsImlhdCI6MTYzMTY4OTMwMywiZXhwIjoxNjMxNzc1NzAzfQ.zYvdpjTq4wJrul5dPEKP43Hrd35JsJYjpNWhfLcj4BQ

{
    "content": "content 3",
    "recipe": "61381c56900dc801dc66035d",
    "user": "6141811deeaa40803222901f"
}

###

POST https://polar-reaches-30197.herokuapp.com/notes
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDE4MTFkZWVhYTQwODAzMjIyOTAxZiIsImlhdCI6MTYzMTY4OTMwMywiZXhwIjoxNjMxNzc1NzAzfQ.zYvdpjTq4wJrul5dPEKP43Hrd35JsJYjpNWhfLcj4BQ

{
    "content": "content",
    "recipe": "61381c56900dc801dc66035d",
    "user": "6141811deeaa40803222901f"
}

###

DELETE https://polar-reaches-30197.herokuapp.com/notes/6142373890e59ec0c14612f0
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDE4MTFkZWVhYTQwODAzMjIyOTAxZiIsImlhdCI6MTYzMTY4OTMwMywiZXhwIjoxNjMxNzc1NzAzfQ.zYvdpjTq4wJrul5dPEKP43Hrd35JsJYjpNWhfLcj4BQ

###

POST http://localhost:5000/user/addToFavs
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDE4MTFkZWVhYTQwODAzMjIyOTAxZiIsImlhdCI6MTYzMTY4OTMwMywiZXhwIjoxNjMxNzc1NzAzfQ.zYvdpjTq4wJrul5dPEKP43Hrd35JsJYjpNWhfLcj4BQ

{
    "recipeId": "614662b4b2f96f26429aae97",
    "userId": "614669e60fab352db951c448"
}

###

POST http://localhost:5000/user/like
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDE4MTFkZWVhYTQwODAzMjIyOTAxZiIsImlhdCI6MTYzMTY4OTMwMywiZXhwIjoxNjMxNzc1NzAzfQ.zYvdpjTq4wJrul5dPEKP43Hrd35JsJYjpNWhfLcj4BQ

{
    "recipeId": "614658830b81b06b92a7aa94",
    "userId": "61422ef3257c69006799ed27"
}

###
GET https://polar-reaches-30197.herokuapp.com/user
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDE4MTFkZWVhYTQwODAzMjIyOTAxZiIsImlhdCI6MTYzMTY4OTMwMywiZXhwIjoxNjMxNzc1NzAzfQ.zYvdpjTq4wJrul5dPEKP43Hrd35JsJYjpNWhfLcj4BQ

###

GET http://localhost:5000/user/51422ef3257c69006799ed27
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDE4MTFkZWVhYTQwODAzMjIyOTAxZiIsImlhdCI6MTYzMTY4OTMwMywiZXhwIjoxNjMxNzc1NzAzfQ.zYvdpjTq4wJrul5dPEKP43Hrd35JsJYjpNWhfLcj4BQ

###

GET http://localhost:5000/user/61422ef3257c69006799ed27
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDE4MTFkZWVhYTQwODAzMjIyOTAxZiIsImlhdCI6MTYzMTY4OTMwMywiZXhwIjoxNjMxNzc1NzAzfQ.zYvdpjTq4wJrul5dPEKP43Hrd35JsJYjpNWhfLcj4BQ

###
POST http://localhost:5000/comments
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDE4MTFkZWVhYTQwODAzMjIyOTAxZiIsImlhdCI6MTYzMTY4OTMwMywiZXhwIjoxNjMxNzc1NzAzfQ.zYvdpjTq4wJrul5dPEKP43Hrd35JsJYjpNWhfLcj4BQ

{
    "content": "content",
    "recipeId": "614658830b81b06b92a7aa94",
    "userId": "61422ef3257c69006799ed27"
}

###
GET http://localhost:5000/comments/614658830b81b06b92a7aa94
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDE4MTFkZWVhYTQwODAzMjIyOTAxZiIsImlhdCI6MTYzMTY4OTMwMywiZXhwIjoxNjMxNzc1NzAzfQ.zYvdpjTq4wJrul5dPEKP43Hrd35JsJYjpNWhfLcj4BQ

###
PATCH http://localhost:5000/comments/614a65bc3aae745920de5558
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDE4MTFkZWVhYTQwODAzMjIyOTAxZiIsImlhdCI6MTYzMTY4OTMwMywiZXhwIjoxNjMxNzc1NzAzfQ.zYvdpjTq4wJrul5dPEKP43Hrd35JsJYjpNWhfLcj4BQ

{
    "content": "content 2",
    "userId": "61422ef3257c69006799ed27"
}

###
DELETE http://localhost:5000/comments/614a65bc3aae745920de5558
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDE4MTFkZWVhYTQwODAzMjIyOTAxZiIsImlhdCI6MTYzMTY4OTMwMywiZXhwIjoxNjMxNzc1NzAzfQ.zYvdpjTq4wJrul5dPEKP43Hrd35JsJYjpNWhfLcj4BQ

{
    "userId": "61422ef3257c69006799ed27"
}
